spring:
  profiles:
    active: dev

  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    username: ${emailUsername}
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


base_url: ${baseUrl}
admin-password: ${adPassword}

flutter-wave.public-key: ${fPub}
flutter-wave.secret-key: ${fSec}

