spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://ec2-34-224-226-38.compute-1.amazonaws.com:5432/d93g60lnivgou8
    username: dabenpyscotvli
    password: ${dbPassword}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    username: chukwumaebubemiracle97@gmail.com
    password: ${emailPassword}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


base_url: ${baseUrl}
admin-password: ${adPassword}

